export const STATISTICS_SERVICE_TOKEN = Symbol('STATISTICS_SERVICE_TOKEN')
export const STATISTICS_REPOSITORY_TOKEN = Symbol('STATISTICS_REPOSITORY_TOKEN')
export const STATISTICS_NOTIFICATION_EVENT_NAME = 'questions.done'
